In [3]:
import numpy as np 

# X = (hours sleeping, hours studying), y = score on test 
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float) 
y = np.array(([92], [86], [89]), dtype=float) 
print("Input (raw):")
print(X) 
print("Output (raw):")
print(y) 

# Scale units 
X = X / np.amax(X, axis=0)  # Maximum of X array 
y = y / 100  # Max test score is 100 
print("\nInput (scaled):")
print(X) 
print("Output (scaled):")
print(y) 

class Neural_Network(object): 
    def __init__(self): 
        # Parameters 
        self.inputSize = 2 
        self.outputSize = 1 
        self.hiddenSize = 3 
        
        # Weights 
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize)  # (2x3) weight matrix from input to hidden layer 
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize)  # (3x1) weight matrix from hidden to output layer 
    
    def forward(self, X):         
        # Forward propagation through the network 
        self.z = np.dot(X, self.W1)             # Dot product of X (input) and first set of weights 
        self.z2 = self.sigmoid(self.z)          # Activation function 
        self.z3 = np.dot(self.z2, self.W2)      # Dot product of hidden layer and second set of weights 
        o = self.sigmoid(self.z3)               # Final activation function 
        return o  
    
    def sigmoid(self, s): 
        # Activation function  
        return 1 / (1 + np.exp(-s)) 
    
    def sigmoidPrime(self, s): 
        # Derivative of sigmoid 
        return s * (1 - s) 
    
    def backward(self, X, y, o): 
        # Backward propagate through the network 
        self.o_error = y - o                            # Error in output 
        self.o_delta = self.o_error * self.sigmoidPrime(o)  # Applying derivative of sigmoid to error 
        
        self.z2_error = self.o_delta.dot(self.W2.T)      # Z2 error: how much our hidden layer weights contributed to output error 
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.z2)  # Applying derivative of sigmoid to z2 error 
        
        # Adjusting weights 
        self.W1 += X.T.dot(self.z2_delta)                # Adjusting first set (input --> hidden) weights 
        self.W2 += self.z2.T.dot(self.o_delta)           # Adjusting second set (hidden --> output) weights 
    
    def train(self, X, y): 
        o = self.forward(X) 
        self.backward(X, y, o)

# Training the Neural Network
NN = Neural_Network()
for i in range(1000):  # Train the network 1,000 times
    NN.train(X, y)
    if i % 100 == 0:  # Print every 100 steps
        print(f"\nIteration {i}")
        print("Predicted Output: \n" + str(NN.forward(X)))
        print("Loss: \n" + str(np.mean(np.square(y - NN.forward(X)))))  # Mean sum squared loss


Input (raw):
[[2. 9.]
 [1. 5.]
 [3. 6.]]
Output (raw):
[[92.]
 [86.]
 [89.]]

Input (scaled):
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Output (scaled):
[[0.92]
 [0.86]
 [0.89]]

Iteration 0
Predicted Output: 
[[0.89756227]
 [0.87101963]
 [0.91906774]]
Loss: 
0.0004899392145449162

Iteration 100
Predicted Output: 
[[0.89359908]
 [0.86636096]
 [0.91445894]]
Loss: 
0.0004452367461747736

Iteration 200
Predicted Output: 
[[0.89402975]
 [0.86625759]
 [0.91352288]]
Loss: 
0.0004223124693753903

Iteration 300
Predicted Output: 
[[0.89445094]
 [0.86623154]
 [0.91269685]]
Loss: 
0.0004022444886697146

Iteration 400
Predicted Output: 
[[0.89482962]
 [0.86623468]
 [0.91193945]]
Loss: 
0.0003845862209601074

Iteration 500
Predicted Output: 
[[0.89517101]
 [0.86626032]
 [0.91124259]]
Loss: 
0.00036897261632015525

Iteration 600
Predicted Output: 
[[0.89547992]
 [0.86630337]
 [0.91059954]]
Loss: 
0.00035510250568966743

Iteration 700
Predicted Output: 
[[0.89576048