In [1]:
import numpy as np 

X = np.array(([0,0],[0,1],[1,0],[1,1]), dtype=float) 
y = np.array(([0],[1],[1],[1]), dtype=float) 
print("Input (raw):")
print(X) 
print("Output (raw):")
print(y) 

X = X / np.amax(X, axis=0)   
y = y / 100 
print("\nInput (scaled):")
print(X) 
print("Output (scaled):")
print(y) 

class Neural_Network(object): 
    def __init__(self): 
        self.inputSize = 2 
        self.outputSize = 1 
        self.hiddenSize = 3 
        
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize)   
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize)  
    
    def forward(self, X):         
        self.z = np.dot(X, self.W1)        
        self.z2 = self.sigmoid(self.z)      
        self.z3 = np.dot(self.z2, self.W2)     
        o = self.sigmoid(self.z3)               
        return o  
    
    def sigmoid(self, s): 
        return 1 / (1 + np.exp(-s)) 
    
    def sigmoidPrime(self, s): 
        return s * (1 - s) 
    
    def backward(self, X, y, o): 
        self.o_error = y - o                             
        self.o_delta = self.o_error * self.sigmoidPrime(o)   
        
        self.z2_error = self.o_delta.dot(self.W2.T)     
         
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.z2) 
        
        
        self.W1 += X.T.dot(self.z2_delta)                
        self.W2 += self.z2.T.dot(self.o_delta)           
    
    def train(self, X, y): 
        o = self.forward(X) 
        self.backward(X, y, o)

NN = Neural_Network()
for i in range(1000):  
    NN.train(X, y)
    if i % 100 == 0: 
        print(f"\nIteration {i}")
        print("Predicted Output: \n" + str(NN.forward(X)))
        print("Loss: \n" + str(np.mean(np.square(y - NN.forward(X))))) 


Input (raw):
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Output (raw):
[[0.]
 [1.]
 [1.]
 [1.]]

Input (scaled):
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Output (scaled):
[[0.  ]
 [0.01]
 [0.01]
 [0.01]]

Iteration 0
Predicted Output: 
[[0.32314496]
 [0.25153146]
 [0.34726083]
 [0.2666246 ]]
Loss: 
0.0855902915357951

Iteration 100
Predicted Output: 
[[0.05881605]
 [0.02294905]
 [0.05311549]
 [0.02141065]]
Loss: 
0.0014040386400638153

Iteration 200
Predicted Output: 
[[0.04393206]
 [0.01544805]
 [0.03551074]
 [0.0133951 ]]
Loss: 
0.0006555080230932921

Iteration 300
Predicted Output: 
[[0.03718053]
 [0.01237849]
 [0.02820157]
 [0.01030311]]
Loss: 
0.0004298595739118283

Iteration 400
Predicted Output: 
[[0.03307912]
 [0.01062889]
 [0.02404062]
 [0.00860897]]
Loss: 
0.0003234243559801945

Iteration 500
Predicted Output: 
[[0.03023622]
 [0.00947199]
 [0.02130166]
 [0.0075217 ]]
Loss: 
0.00026209432573081736

Iteration 600
Predicted Output: 
[[0.02810994]
 [0.0086389 ]
 [0.0193398 ]
 [0.00675745]]
