In [ ]:
import numpy as np

def matrix_composition(R, S):
    n = R.shape[0]
    composition = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            composition[i, j] = max(min(R[i, k], S[k, j]) for k in range(n))
    return composition


R = np.array([
    [1, 0, 1],
    [0, 1, 1],
    [0, 0, 1]
])

S = np.array([
    [1, 1, 0],
    [0, 1, 0],
    [1, 0, 1]
])

R_comp_S = matrix_composition(R, S)

S_comp_R = matrix_composition(S, R)

print("R ∘ S:\n", R_comp_S)
print("S ∘ R:\n", S_comp_R)

if np.array_equal(R_comp_S, S_comp_R):
    print("R ∘ S is equal to S ∘ R")
else:
    print("R ∘ S is not equal to S ∘ R")


R ∘ S:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 0. 1.]]
S ∘ R:
 [[1. 1. 1.]
 [0. 1. 1.]
 [1. 0. 1.]]
R ∘ S is not equal to S ∘ R
